var video1 = "<video id='video1' autoplay='autoplay' src='video/ticTacToeSelect.mp4'></video>";
var video2 = "<video id='video2' autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/firstPlay.mp4'></video>";
var video3 = "<video id='video3' autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/putXInCenter.mp4'></video>";
var video4 = "<video id='video4' autoplay='autoplay' src='video/AwaitingFirstStrike.mp4'></video>";
var video5 = "<video id='video5' autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/putXInCenter.mp4'></video>";
var video6 = "<video id='video6' autoplay='autoplay' src='video/WarGamesGreetingsProf.mp4'></video>";
var video7 = "<video id='video7' autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/defcon.mp4'></video>";
var video8 = "<video id='video8' autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/defcon3.mp4'></video>";
var video9 = "<video id='video9' autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/defcon2.mp4'></video>";
var video10 = "<video id='video10'  autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/defcon1.mp4'></video>";
var video11 = "<video id='video11'  autoplay='autoplay' src='video/10numbers.mp4'></video>";
var video12 = "<video id='video12'  autoplay='autoplay' src='video/7learnGodDammit.mp4'></video>";
var video13 = "<video id='video13'  autoplay='autoplay' src='video/xOrO.mp4'></video>";
var video14 = "<video id='video14'  autoplay='autoplay' src='video/itsLearning.mp4'></video>";
var video15 = "<video id='video15'  autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/finalSceneXwin.mp4'></video>";
var video16 = "<video id='video16'  autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/FinalSceneOWins.mp4'></video>";
var video17 = "<video id='video17'  autoplay='autoplay' src='http://s3.amazonaws.com/FitMuses_Photos/Domen/stalemate.mp4'></video>"